//dasdasdas
//dasd
const event = {
  watchPREvents: { labels: true },
  watchFilters: {},
  repoPath: '.github/workflows/gitstream.yml',
  gitstreamGatesCheckId: 15293278743,
  repo: 'EuropeanPaintings',
  owner: 'yeelali14',
  branch: 'LINBEE-1628-2',
  installationId: 39985136,
  pullRequestNumber: 869,
  headSha: 'e5042f99dfa2ab9ac53a4fa3a3aebf740bf33345',
  baseRef: 'main',
  triggeredBy: 'yeelali14',
  triggeredPREvent: 'opened',
  source: 'github',
  ddApiKey: '123',
  env: 'local',
  creator: 'yeelali14',
  analytics_url: 'http://yeela.ngrok.io/analytics',
  analyticsHttpApiUrl: 'https://api.amplitude.com/2/httpapi',
  analyticsKey: '123',
  segmentServiceUrl: 'https://api.segment.io',
  segmentWriteKey: 'Ts5ERU2KWfeE50DekgnG6t5g5Rp0wFRA',
  prContext: {
    isFullyInstalled: true,
    title: 'LINBEE-1628-2',
    approvals: [],
    requested_changes: [],
    author: 'yeelali14',
    description:
      'WyFbd29ya2VyQl0oaHR0cHM6Ly9pbWcuc2hpZWxkcy5pby9lbmRwb2ludD91cmw9aHR0cHMlM0ElMkYlMkZ3b3JrZXJiLmxpbmVhcmIuaW8lMkZ2MiUyRmJhZGdlJTJGcHJpdmF0ZSUyRlUyRnNkR1ZrWDE4dXlJOUVmdFFZR3U2SnJIV3FZTWxiN2x0RVJxODRNJTJGY29sbGFib3JhdGlvbi5zdmclM0ZjYWNoZVNlY29uZHMlM0Q2MCldKGh0dHBzOi8vd29ya2VyYi5saW5lYXJiLmlvL3YyL2JhZGdlL2NvbGxhYm9yYXRpb24tcGFnZT9tYWdpY0xpbmtJZD1lSXNabjM4KQ==',
    checks: [
      { name: 'gitStream.cm', status: 'in_progress' },
      { name: '- add-label@v1', status: 'completed', conclusion: 'success' },
      {
        name: 'gitStream workflow automation',
        status: 'completed',
        conclusion: 'success',
      },
    ],
    created_at: '2023-07-24T14:26:31Z',
    draft: false,
    mergeable: true,
    labels: ['1 min review'],
    reviewers: [],
    status: 'open',
    updated_at: '2023-07-24T14:27:57Z',
    assignees: [],
    contributors: [
      { login: 'lkilpatrick', name: 'Luke Kilpatrick' },
      { login: 'Yaarash', name: 'Yaara Shoham' },
      { login: 'ShakedZrihen', name: 'shaked zohar' },
      { login: 'yeelali14', name: 'Yeela Lifshitz' },
      { login: 'paparoach14', name: null },
      { login: 'ShaniBelisha', name: 'Shani' },
      { login: 'EladKohavi', name: 'Elad Kohavi' },
    ],
    paths: [
      { name: 'another.cm' },
      { name: 'cmbackup.yml' },
      { name: 'gitstream.cm' },
    ],
    author_teams: [],
    author_is_org_member: true,
    comments: [],
    reviews: [],
    conversations: [],
    unresolved_threads: 0,
  },
  hasCmRepo: false,
  providerRepoId: 400902592,
  isNewCommit: true,
  trigger_id: '4e3f5714-87c8-43c4-9767-bdda7a126378',
  admins: [],
  dryRun: false,
  onlyRulesFilesChanges: false,
  action: 'invoke-github-action@v1',
  args: {
    owner: 'yeelali14',
    repo: 'pasha',
    workflow: '.github/workflows/example.yml',
    ref: 'yeelali14-patch-13',
    inputs: { commit_sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d' },
    check_name: 'wow',
  },
  shouldExecute: true,
  ref: 'e5042f99dfa2ab9ac53a4fa3a3aebf740bf33345',
  checkName: 'invoke-github-action@v1',
  updatedBy: 'github-actions-consumer: actions executor',
};

const action = {
  wokflow: '.github/workflows/example.yml',
  org: 'github-yeelali14',
  repo: 'EuropeanPaintings',
  headSha: 'bd4f8eb984e4920a10a9822736c372d161e69cc1',
  prNumber: 869,
  checkName: 'wow',
  branch: 'yeelali14-patch-13',
  workflowId: 62113785,
};
//dasdasdfsdfssfsdfsfdsfsd