//new service

const inputs = {
    watchPREvents: {},
    watchFilters: {},
    repoPath: '.github/workflows/gitstream.yml',
    gitstreamGatesCheckId: 19958023935,
    repo: 'EuropeanPaintings',
    owner: 'yeelali14',
    branch: 'LINBEE-362-2',
    installationId: 45479489,
    pullRequestNumber: 1046,
    headSha: 'd9990f0f3970595b6198748e7992aabc59c091be',
    baseRef: 'main',
    baseSha: 'd848dd0439caa11c69156fb6ab2400cf3c99f0d9',
    visibility: 'public',
    triggeredBy: 'yeelali14',
    triggeredPREvent: 'opened',
    source: 'github',
    ddApiKey: '123',
    env: 'local',
    creator: 'yeelali14',
    analytics_url: 'http://yeela.ngrok.io/analytics',
    analyticsHttpApiUrl: 'https://api.amplitude.com/2/httpapi',
    analyticsKey: '123',
    segmentServiceUrl: 'https://api.segment.io',
    segmentWriteKey: 'Ts5ERU2KWfeE50DekgnG6t5g5Rp0wFRA',
    prContext: {
      isFullyInstalled: true,
      title: 'test',
      approvals: [],
      requested_changes: [],
      author: 'yeelali14',
      description: '',
      checks: [ [Object], [Object] ],
      created_at: '2023-12-26T11:03:55Z',
      draft: false,
      mergeable: true,
      labels: [],
      reviewers: [],
      status: 'open',
      updated_at: '2023-12-26T11:03:55Z',
      assignees: [],
      contributors: [
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object]
      ],
      paths: [
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object],
        [Object], [Object], [Object]
      ],
      author_teams: [],
      author_is_org_member: true,
      comments: [],
      reviews: [],
      conversations: [],
      unresolved_threads: 0,
      number: 1046,
      url: 'https://github.com/yeelali14/EuropeanPaintings/pull/1046'
    },
    hasCmRepo: false,
    providerRepoId: 400902592,
    isNewCommit: true,
    trigger_id: 'd04d94aa-8e78-4ca1-b023-2b750d238efc',
    headHttpUrl: 'https://github.com/yeelali14/EuropeanPaintings',
    explicitTriggers: { '.cm/4554.cm': { shouldBeTriggered: true } },
    webhookEventName: 'pull_request_opened',
    githubToken: '123',
    eventAction: 'opened',
    mergeCommitSha: '',
    admins: [],
    dryRun: false,
    onlyRulesFilesChanges: false,
    automationName: '4554/senior_review',
    action: 'add-label@v1',
    args: { label: 'dryrun' },
    isTriggered: true,
    ref: 'd9990f0f3970595b6198748e7992aabc59c091be',
    checkName: 'add-label@v1',
    updatedBy: 'github-actions-consumer: actions executor'
  }

  adjashdkjahskdj