const check_run_completed = {
  action: 'created',
  check_run: {
    id: 15167405603,
    name: 'linbee-1503',
    node_id: 'CR_kwDOJOZy_s8AAAADiAw-Iw',
    head_sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
    external_id: '',
    url: 'https://api.github.com/repos/yeelali14/pasha/check-runs/15167405603',
    html_url: 'https://github.com/yeelali14/pasha/runs/15167405603',
    details_url: 'https://github.com/yeelali14/pasha/runs/15167405603',
    status: 'completed',
    conclusion: 'success',
    started_at: '2023-07-19T12:55:46Z',
    completed_at: '2023-07-19T12:55:46Z',
    output: {
      title: null,
      summary: null,
      text: null,
      annotations_count: 0,
      annotations_url:
        'https://api.github.com/repos/yeelali14/pasha/check-runs/15167405603/annotations',
    },
    check_suite: {
      id: 14410311965,
      node_id: 'CS_kwDOJOZy_s8AAAADWuvpHQ',
      head_branch: 'linbee-1503-updated',
      head_sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
      status: 'completed',
      conclusion: 'success',
      url: 'https://api.github.com/repos/yeelali14/pasha/check-suites/14410311965',
      before: '0000000000000000000000000000000000000000',
      after: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
      pull_requests: [
        {
          url: 'https://api.github.com/repos/yeelali14/pasha/pulls/18',
          id: 1440942501,
          number: 18,
          head: {
            ref: 'linbee-1503-updated',
            sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
            repo: {
              id: 619082494,
              url: 'https://api.github.com/repos/yeelali14/pasha',
              name: 'pasha',
            },
          },
          base: {
            ref: 'main',
            sha: 'd1b3c8142eb67dab3c12135eaf8aa24d90f6ade4',
            repo: {
              id: 619082494,
              url: 'https://api.github.com/repos/yeelali14/pasha',
              name: 'pasha',
            },
          },
        },
      ],
      app: {
        id: 15368,
        slug: 'github-actions',
        node_id: 'MDM6QXBwMTUzNjg=',
        owner: {
          login: 'github',
          id: 9919,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5MTk=',
          avatar_url: 'https://avatars.githubusercontent.com/u/9919?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/github',
          html_url: 'https://github.com/github',
          followers_url: 'https://api.github.com/users/github/followers',
          following_url:
            'https://api.github.com/users/github/following{/other_user}',
          gists_url: 'https://api.github.com/users/github/gists{/gist_id}',
          starred_url:
            'https://api.github.com/users/github/starred{/owner}{/repo}',
          subscriptions_url:
            'https://api.github.com/users/github/subscriptions',
          organizations_url: 'https://api.github.com/users/github/orgs',
          repos_url: 'https://api.github.com/users/github/repos',
          events_url: 'https://api.github.com/users/github/events{/privacy}',
          received_events_url:
            'https://api.github.com/users/github/received_events',
          type: 'Organization',
          site_admin: false,
        },
        name: 'GitHub Actions',
        description: 'Automate your workflow from idea to production',
        external_url: 'https://help.github.com/en/actions',
        html_url: 'https://github.com/apps/github-actions',
        created_at: '2018-07-30T09:30:17Z',
        updated_at: '2019-12-10T19:04:12Z',
        permissions: {
          actions: 'write',
          administration: 'read',
          checks: 'write',
          contents: 'write',
          deployments: 'write',
          discussions: 'write',
          issues: 'write',
          merge_queues: 'write',
          metadata: 'read',
          packages: 'write',
          pages: 'write',
          pull_requests: 'write',
          repository_hooks: 'write',
          repository_projects: 'write',
          security_events: 'write',
          statuses: 'write',
          vulnerability_alerts: 'read',
        },
        events: [
          'branch_protection_rule',
          'check_run',
          'check_suite',
          'create',
          'delete',
          'deployment',
          'deployment_status',
          'discussion',
          'discussion_comment',
          'fork',
          'gollum',
          'issues',
          'issue_comment',
          'label',
          'merge_group',
          'milestone',
          'page_build',
          'project',
          'project_card',
          'project_column',
          'public',
          'pull_request',
          'pull_request_review',
          'pull_request_review_comment',
          'push',
          'registry_package',
          'release',
          'repository',
          'repository_dispatch',
          'status',
          'watch',
          'workflow_dispatch',
          'workflow_run',
        ],
      },
      created_at: '2023-07-19T12:30:43Z',
      updated_at: '2023-07-19T12:31:19Z',
    },
    app: {
      id: 15368,
      slug: 'github-actions',
      node_id: 'MDM6QXBwMTUzNjg=',
      owner: {
        login: 'github',
        id: 9919,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5MTk=',
        avatar_url: 'https://avatars.githubusercontent.com/u/9919?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github',
        html_url: 'https://github.com/github',
        followers_url: 'https://api.github.com/users/github/followers',
        following_url:
          'https://api.github.com/users/github/following{/other_user}',
        gists_url: 'https://api.github.com/users/github/gists{/gist_id}',
        starred_url:
          'https://api.github.com/users/github/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github/subscriptions',
        organizations_url: 'https://api.github.com/users/github/orgs',
        repos_url: 'https://api.github.com/users/github/repos',
        events_url: 'https://api.github.com/users/github/events{/privacy}',
        received_events_url:
          'https://api.github.com/users/github/received_events',
        type: 'Organization',
        site_admin: false,
      },
      name: 'GitHub Actions',
      description: 'Automate your workflow from idea to production',
      external_url: 'https://help.github.com/en/actions',
      html_url: 'https://github.com/apps/github-actions',
      created_at: '2018-07-30T09:30:17Z',
      updated_at: '2019-12-10T19:04:12Z',
      permissions: {
        actions: 'write',
        administration: 'read',
        checks: 'write',
        contents: 'write',
        deployments: 'write',
        discussions: 'write',
        issues: 'write',
        merge_queues: 'write',
        metadata: 'read',
        packages: 'write',
        pages: 'write',
        pull_requests: 'write',
        repository_hooks: 'write',
        repository_projects: 'write',
        security_events: 'write',
        statuses: 'write',
        vulnerability_alerts: 'read',
      },
      events: [
        'branch_protection_rule',
        'check_run',
        'check_suite',
        'create',
        'delete',
        'deployment',
        'deployment_status',
        'discussion',
        'discussion_comment',
        'fork',
        'gollum',
        'issues',
        'issue_comment',
        'label',
        'merge_group',
        'milestone',
        'page_build',
        'project',
        'project_card',
        'project_column',
        'public',
        'pull_request',
        'pull_request_review',
        'pull_request_review_comment',
        'push',
        'registry_package',
        'release',
        'repository',
        'repository_dispatch',
        'status',
        'watch',
        'workflow_dispatch',
        'workflow_run',
      ],
    },
    pull_requests: [
      {
        url: 'https://api.github.com/repos/yeelali14/pasha/pulls/18',
        id: 1440942501,
        number: 18,
        head: {
          ref: 'linbee-1503-updated',
          sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
          repo: {
            id: 619082494,
            url: 'https://api.github.com/repos/yeelali14/pasha',
            name: 'pasha',
          },
        },
        base: {
          ref: 'main',
          sha: 'd1b3c8142eb67dab3c12135eaf8aa24d90f6ade4',
          repo: {
            id: 619082494,
            url: 'https://api.github.com/repos/yeelali14/pasha',
            name: 'pasha',
          },
        },
      },
    ],
  },
  repository: {
    id: 619082494,
    node_id: 'R_kgDOJOZy_g',
    name: 'pasha',
    full_name: 'yeelali14/pasha',
    private: true,
    owner: {
      login: 'yeelali14',
      id: 52451294,
      node_id: 'MDQ6VXNlcjUyNDUxMjk0',
      avatar_url: 'https://avatars.githubusercontent.com/u/52451294?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/yeelali14',
      html_url: 'https://github.com/yeelali14',
      followers_url: 'https://api.github.com/users/yeelali14/followers',
      following_url:
        'https://api.github.com/users/yeelali14/following{/other_user}',
      gists_url: 'https://api.github.com/users/yeelali14/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/yeelali14/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/yeelali14/subscriptions',
      organizations_url: 'https://api.github.com/users/yeelali14/orgs',
      repos_url: 'https://api.github.com/users/yeelali14/repos',
      events_url: 'https://api.github.com/users/yeelali14/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/yeelali14/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/yeelali14/pasha',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/yeelali14/pasha',
    forks_url: 'https://api.github.com/repos/yeelali14/pasha/forks',
    keys_url: 'https://api.github.com/repos/yeelali14/pasha/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/yeelali14/pasha/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/yeelali14/pasha/teams',
    hooks_url: 'https://api.github.com/repos/yeelali14/pasha/hooks',
    issue_events_url:
      'https://api.github.com/repos/yeelali14/pasha/issues/events{/number}',
    events_url: 'https://api.github.com/repos/yeelali14/pasha/events',
    assignees_url:
      'https://api.github.com/repos/yeelali14/pasha/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/yeelali14/pasha/branches{/branch}',
    tags_url: 'https://api.github.com/repos/yeelali14/pasha/tags',
    blobs_url: 'https://api.github.com/repos/yeelali14/pasha/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/yeelali14/pasha/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/yeelali14/pasha/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/yeelali14/pasha/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/yeelali14/pasha/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/yeelali14/pasha/languages',
    stargazers_url: 'https://api.github.com/repos/yeelali14/pasha/stargazers',
    contributors_url:
      'https://api.github.com/repos/yeelali14/pasha/contributors',
    subscribers_url: 'https://api.github.com/repos/yeelali14/pasha/subscribers',
    subscription_url:
      'https://api.github.com/repos/yeelali14/pasha/subscription',
    commits_url: 'https://api.github.com/repos/yeelali14/pasha/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/yeelali14/pasha/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/yeelali14/pasha/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/yeelali14/pasha/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/yeelali14/pasha/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/yeelali14/pasha/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/yeelali14/pasha/merges',
    archive_url:
      'https://api.github.com/repos/yeelali14/pasha/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/yeelali14/pasha/downloads',
    issues_url: 'https://api.github.com/repos/yeelali14/pasha/issues{/number}',
    pulls_url: 'https://api.github.com/repos/yeelali14/pasha/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/yeelali14/pasha/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/yeelali14/pasha/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/yeelali14/pasha/labels{/name}',
    releases_url: 'https://api.github.com/repos/yeelali14/pasha/releases{/id}',
    deployments_url: 'https://api.github.com/repos/yeelali14/pasha/deployments',
    created_at: '2023-03-26T08:00:50Z',
    updated_at: '2023-07-05T09:02:18Z',
    pushed_at: '2023-07-19T12:30:21Z',
    git_url: 'git://github.com/yeelali14/pasha.git',
    ssh_url: 'git@github.com:yeelali14/pasha.git',
    clone_url: 'https://github.com/yeelali14/pasha.git',
    svn_url: 'https://github.com/yeelali14/pasha',
    homepage: null,
    size: 65,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 15,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'private',
    forks: 0,
    open_issues: 15,
    watchers: 0,
    default_branch: 'main',
  },
  sender: {
    login: 'yeelali14',
    id: 52451294,
    node_id: 'MDQ6VXNlcjUyNDUxMjk0',
    avatar_url: 'https://avatars.githubusercontent.com/u/52451294?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/yeelali14',
    html_url: 'https://github.com/yeelali14',
    followers_url: 'https://api.github.com/users/yeelali14/followers',
    following_url:
      'https://api.github.com/users/yeelali14/following{/other_user}',
    gists_url: 'https://api.github.com/users/yeelali14/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/yeelali14/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/yeelali14/subscriptions',
    organizations_url: 'https://api.github.com/users/yeelali14/orgs',
    repos_url: 'https://api.github.com/users/yeelali14/repos',
    events_url: 'https://api.github.com/users/yeelali14/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/yeelali14/received_events',
    type: 'User',
    site_admin: false,
  },
  installation: {
    id: 39802257,
    node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzk4MDIyNTc=',
  },
};


const checks_pr = {
    total_count: 1,
    check_runs: [
      {
        id: 15201039955,
        name: 'Create/Update a commit Check Run',
        node_id: 'CR_kwDOJOZy_s8AAAADig12Uw',
        head_sha: '2539d9d90f606fa77c4b22239ccf1e9cab56314d',
        external_id: 'a81d0fee-2a51-5a7b-bfac-5e4df2e92e8f',
        url: 'https://api.github.com/repos/yeelali14/pasha/check-runs/15201039955',
        html_url: 'https://github.com/yeelali14/pasha/actions/runs/5610792567/jobs/10266258446',
        details_url: 'https://github.com/yeelali14/pasha/actions/runs/5610792567/jobs/10266258446',
        status: 'completed',
        conclusion: 'success',
        started_at: '2023-07-20T12:10:12Z',
        completed_at: '2023-07-20T12:10:14Z',
        output: [Object],
        check_suite: [Object],
        app: [Object],
        pull_requests: [Array]
      }
    ]
  }