const paams = {
    watchPREvents: {},
    watchFilters: {},
    repoPath: '.github/workflows/gitstream.yml',
    gitstreamGatesCheckId: 16678899043,
    repo: 'pasha',
    owner: 'yeelali14',
    branch: 'yeelali14-patch-59',
    installationId: 41686204,
    pullRequestNumber: 75,
    headSha: 'c8b14abff34ec9d06bf2d8e006cf063d8299e0da',
    baseRef: 'main',
    triggeredBy: 'yeelali14',
    triggeredPREvent: 'created',
    source: 'github',
    ddApiKey: '123',
    env: 'local',
    creator: 'yeelali14',
    analytics_url: 'http://yeela.ngrok.io/analytics',
    analyticsHttpApiUrl: 'https://api.amplitude.com/2/httpapi',
    analyticsKey: '123',
    segmentServiceUrl: 'https://api.segment.io',
    segmentWriteKey: 'Ts5ERU2KWfeE50DekgnG6t5g5Rp0wFRA',
    prContext: {
      isFullyInstalled: true,
      title: 'Update README.md',
      approvals: [],
      requested_changes: [],
      author: 'yeelali14',
      description:
        'WyFbd29ya2VyQl0oaHR0cHM6Ly9pbWcuc2hpZWxkcy5pby9lbmRwb2ludD91cmw9aHR0cHMlM0ElMkYlMkZ3b3JrZXJiLmxpbmVhcmIuaW8lMkZ2MiUyRmJhZGdlJTJGcHJpdmF0ZSUyRlUyRnNkR1ZrWDE5Um9wbldsVllGYlBqNU81VngwY1BtTjVVeWhtdHQ0dlElMkZjb2xsYWJvcmF0aW9uLnN2ZyUzRmNhY2hlU2Vjb25kcyUzRDYwKV0oaHR0cHM6Ly93b3JrZXJiLmxpbmVhcmIuaW8vdjIvYmFkZ2UvY29sbGFib3JhdGlvbi1wYWdlP21hZ2ljTGlua0lkPWFZTFlpd2wp',
      checks: [[Object], [Object], [Object], [Object], [Object], [Object]],
      created_at: '2023-09-11T13:57:18Z',
      draft: false,
      mergeable: true,
      labels: ['dispatch check'],
      reviewers: [],
      status: 'open',
      updated_at: '2023-09-11T13:59:25Z',
      assignees: [],
      contributors: [[Object], [Object], [Object], [Object]],
      paths: [[Object], [Object], [Object]],
      author_teams: [],
      author_is_org_member: true,
      comments: [[Object], [Object]],
      reviews: [],
      conversations: [],
      unresolved_threads: 0,
      number: 75,
      url: 'https://github.com/yeelali14/pasha/pull/75'
    },
    hasCmRepo: false,
    providerRepoId: 619082494,
    trigger_id: '2f92b2c1-1d6b-4818-be62-5d474b24065f',
    headHttpUrl: 'https://github.com/yeelali14/pasha',
    explicitTriggers: { '.cm/invoke.cm': { shouldBeTriggered: true } },
    webhookEventName: 'issue_comment_created',
    githubToken: 'ghs_cXFeMFh4TvqeF5XvwHD9y4JWYaihuY081WZN',
    admins: [],
    dryRun: false,
    onlyRulesFilesChanges: false,
    automationName: 'invoke/add_label',
    action: 'add-label@v1',
    args: { label: 'dispatch check' },
    shouldExecute: true,
    ref: 'c8b14abff34ec9d06bf2d8e006cf063d8299e0da',
    checkName: 'add-label@v1',
    updatedBy: 'github-actions-consumer: actions executor',
    check: {
      status: 201,
      url: 'https://api.github.com/repos/yeelali14/pasha/check-runs',
      headers: {
        'access-control-allow-origin': '*',
        'access-control-expose-headers':
          'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
        'cache-control': 'private, max-age=60, s-maxage=60',
        connection: 'close',
        'content-length': '3019',
        'content-security-policy': "default-src 'none'",
        'content-type': 'application/json; charset=utf-8',
        date: 'Mon, 11 Sep 2023 14:00:10 GMT',
        etag: '"344329626340a2c905d6ed0cb0a1bc492cbc63b6c2875ed302fcfc0c399d1013"',
        location: 'https://api.github.com/repos/yeelali14/pasha/check-runs/16678950416',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        server: 'GitHub.com',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
        'x-accepted-github-permissions': 'checks=write',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'deny',
        'x-github-api-version-selected': '2022-11-28',
        'x-github-media-type': 'github.v3; format=json',
        'x-github-request-id': 'EF73:CE0C:3A3D9D0:3AD3CA3:64FF1D69',
        'x-ratelimit-limit': '5000',
        'x-ratelimit-remaining': '4956',
        'x-ratelimit-reset': '1694444204',
        'x-ratelimit-resource': 'core',
        'x-ratelimit-used': '44',
        'x-xss-protection': '0'
      },
      data: {
        id: 16678950416,
        name: '- add-label@v1',
        node_id: 'CR_kwDOJOZy_s8AAAAD4iSWEA',
        head_sha: 'c8b14abff34ec9d06bf2d8e006cf063d8299e0da',
        external_id: '',
        url: 'https://api.github.com/repos/yeelali14/pasha/check-runs/16678950416',
        html_url: 'https://github.com/yeelali14/pasha/runs/16678950416',
        details_url: 'http://gitstream.cm',
        status: 'queued',
        conclusion: null,
        started_at: '2023-09-11T14:00:10Z',
        completed_at: null,
        output: [Object],
        check_suite: [Object],
        app: [Object],
        pull_requests: [Array]
      }
    },
    status: 'completed',
    conclusion: 'success',
    output: { title: 'dispatch check', summary: 'dispatch check' },
    context: { state: 'UPDATE_LABELS', args: { labels: [Array] } }
  };
  