on:
  pull_request:
    types: [synchronize]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: cypress job
      uses: actions/github-script@v3
      env:
        BASE_REF_ARG: "main"
        HEAD_REF_ARG: "CAD-13581-Change-GeneratedCircuit-to-the-QuantumProgram-and-ExecutionCircuit-to-ExecutionProgram"
        PAYLOAD_ARG: "{\"repoPath\":\".github/workflows/gitstream.yml\",\"gitstreamGatesCheckId\":19984455615,\"repo\":\"EuropeanPaintings\",\"owner\":\"yeelali14\",\"branch\":\"escape-test-1\",\"installationId\":45493330,\"pullRequestNumber\":1057,\"headSha\":\"aeebe51b7ad009bb8e314f78f71b348544f8fd04\",\"baseRef\":\"main\",\"baseSha\":\"7eb071de8ec83cef5860ebc093769fc954fe5397\",\"visibility\":\"public\",\"triggeredBy\":\"yeelali14\",\"triggeredPREvent\":\"synchronize\",\"source\":\"github\",\"ddApiKey\":\"123\",\"env\":\"local\",\"creator\":\"yeelali14\",\"analytics_url\":\"http://yeela.ngrok.io/analytics\",\"analyticsHttpApiUrl\":\"https://api.amplitude.com/2/httpapi\",\"analyticsKey\":\"123\",\"segmentServiceUrl\":\"https://api.segment.io\",\"segmentWriteKey\":\"Ts5ERU2KWfeE50DekgnG6t5g5Rp0wFRA\",\"prContext\":{\"isFullyInstalled\":true,\"title\":\"escape test\",\"approvals\":[],\"requested_changes\":[],\"author\":\"yeelali14\",\"description\":\"\",\"checks\":[],\"created_at\":\"2023-12-27T15:32:18Z\",\"draft\":false,\"mergeable\":true,\"labels\":[],\"reviewers\":[\"EladKohavi\",\"ShakedZrihen\"],\"status\":\"open\",\"updated_at\":\"2023-12-27T15:33:55Z\",\"assignees\":[],\"contributors\":[{\"login\":\"lkilpatrick\",\"name\":\"Luke Kilpatrick\"},{\"login\":\"Yaarash\",\"name\":\"Yaara Shoham\"},{\"login\":\"ShakedZrihen\",\"name\":\"shaked zohar\"},{\"login\":\"yeelali14\",\"name\":\"Yeela Lifshitz\"},{\"login\":\"paparoach14\",\"name\":null},{\"login\":\"ShaniBelisha\",\"name\":\"Shani\"},{\"login\":\"EladKohavi\",\"name\":\"Elad Kohavi\"}],\"paths\":[{\"name\":\"2570-1.md\"},{\"name\":\"2570.md\"},{\"name\":\"2693.md\"},{\"name\":\"362.cm\"},{\"name\":\"4291.md\"},{\"name\":\"4554.md\"},{\"name\":\"LINBEE-2402.md\"},{\"name\":\"add-check.md\"},{\"name\":\"another.md\"},{\"name\":\"banana.md\"},{\"name\":\"banana2.md\"},{\"name\":\"cmbackup.md\"},{\"name\":\"cmbackup.yml\"},{\"name\":\"conflicts.md\"},{\"name\":\"elad-bug.md\"},{\"name\":\"gitstream-with-error.md\"},{\"name\":\"gitstream.md\"},{\"name\":\"invoke1.md\"},{\"name\":\"misha.md\"},{\"name\":\"rules-engine-cm.md\"},{\"name\":\"sanity.md\"},{\"name\":\"sanity2.md\"},{\"name\":\"selective-ci-demo.md\"},{\"name\":\"without-review.md\"},{\"name\":\"without-triggers.md\"}],\"author_teams\":[],\"author_is_org_member\":true,\"comments\":[],\"reviews\":[],\"conversations\":[],\"unresolved_threads\":0,\"number\":1057,\"url\":\"https://github.com/yeelali14/EuropeanPaintings/pull/1057\",\"isPrivate\":false,\"target\":\"main\"},\"hasCmRepo\":false,\"providerRepoId\":400902592,\"isNewCommit\":true,\"trigger_id\":\"30a056ec-7503-4d92-9a72-94aa52fb9341\",\"headHttpUrl\":\"https://github.com/yeelali14/EuropeanPaintings\",\"explicitTriggers\":{\".cm/362.cm\":{\"shouldBeTriggered\":true}},\"webhookEventName\":\"pull_request_synchronize\",\"githubToken\":\"***\",\"eventAction\":\"synchronize\",\"mergeCommitSha\":\"\"}"
        URL_ARG: "https://github.com/Classiq-Technologies/Cadmium"
      with:
        script: |
          try {
            function convertToSafeString(input) {
              return (input || '').replace(/['`]/g, "\\$&");
            };
            function escapeApostrophe(input) {
              return (input || '').replace(/'/g, "\\'");
            };
            const base_ref = escapeApostrophe(process.env.BASE_REF_ARG);
            const head_ref = escapeApostrophe(process.env.HEAD_REF_ARG);
            const url = convertToSafeString(process.env.URL_ARG);
            const client_payload = convertToSafeString(process.env.PAYLOAD_ARG);
            core.setOutput('base_ref', base_ref);
            core.setOutput('head_ref', head_ref);
            core.setOutput('url', url);
            core.setOutput('client_payload', client_payload);
          } catch (err) {
            core.error(`Failed producing safe string: ${err}`);
            process.exit(1);
          }

