name: Create GitHub Check on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-check:
    runs-on: ubuntu-latest
    name: Create a Check on PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Create a check run on EuropeanPaintings
        uses: actions/github-script@v3
        id: invoke-check
        env:
          GITHUB_TOKEN: ${{ secrets.PASHA_ACCESS_TOKEN }}
        with:
          script: |
            const head_sha = github.context.sha;
            core.info(`Creating check on commit: ${head_sha}`)
            try {
              const result = await github.checks.create({
                owner: 'yeelali14',
                repo: 'EuropeanPaintings',
                name: 'test-oauth',
                status: 'completed',
                head_sha: head_sha,
                conclusion: 'success'
              });
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
